/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ProviderStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ServiceCategory = { 'plumber' : null } |
  { 'other' : null } |
  { 'hvac' : null } |
  { 'electrician' : null } |
  { 'nurse' : null } |
  { 'cleaner' : null } |
  { 'painter' : null } |
  { 'carpenter' : null };
export interface ServiceProvider {
  'id' : bigint,
  'bio' : string,
  'status' : ProviderStatus,
  'yearsExperience' : bigint,
  'name' : string,
  'email' : string,
  'availability' : string,
  'category' : ServiceCategory,
  'phone' : string,
  'registeredAt' : bigint,
  'location' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveProvider' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getApprovedProviders' : ActorMethod<[], Array<ServiceProvider>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProvider' : ActorMethod<[bigint], [] | [ServiceProvider]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPendingProviders' : ActorMethod<[], Array<ServiceProvider>>,
  'registerProvider' : ActorMethod<
    [string, string, string, ServiceCategory, bigint, string, string, string],
    bigint
  >,
  'rejectProvider' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProviders' : ActorMethod<
    [[] | [ServiceCategory], [] | [string]],
    Array<ServiceProvider>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];