/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProviderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'plumber' : IDL.Null,
  'other' : IDL.Null,
  'hvac' : IDL.Null,
  'electrician' : IDL.Null,
  'nurse' : IDL.Null,
  'cleaner' : IDL.Null,
  'painter' : IDL.Null,
  'carpenter' : IDL.Null,
});
export const ServiceProvider = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'status' : ProviderStatus,
  'yearsExperience' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'availability' : IDL.Text,
  'category' : ServiceCategory,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveProvider' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getApprovedProviders' : IDL.Func([], [IDL.Vec(ServiceProvider)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProvider' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceProvider)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPendingProviders' : IDL.Func([], [IDL.Vec(ServiceProvider)], ['query']),
  'registerProvider' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ServiceCategory,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'rejectProvider' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProviders' : IDL.Func(
      [IDL.Opt(ServiceCategory), IDL.Opt(IDL.Text)],
      [IDL.Vec(ServiceProvider)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProviderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'plumber' : IDL.Null,
    'other' : IDL.Null,
    'hvac' : IDL.Null,
    'electrician' : IDL.Null,
    'nurse' : IDL.Null,
    'cleaner' : IDL.Null,
    'painter' : IDL.Null,
    'carpenter' : IDL.Null,
  });
  const ServiceProvider = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'status' : ProviderStatus,
    'yearsExperience' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'availability' : IDL.Text,
    'category' : ServiceCategory,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveProvider' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getApprovedProviders' : IDL.Func(
        [],
        [IDL.Vec(ServiceProvider)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProvider' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceProvider)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPendingProviders' : IDL.Func(
        [],
        [IDL.Vec(ServiceProvider)],
        ['query'],
      ),
    'registerProvider' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ServiceCategory,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'rejectProvider' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProviders' : IDL.Func(
        [IDL.Opt(ServiceCategory), IDL.Opt(IDL.Text)],
        [IDL.Vec(ServiceProvider)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };