/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ServiceProvider {
    id: bigint;
    bio: string;
    status: ProviderStatus;
    yearsExperience: bigint;
    name: string;
    email: string;
    availability: string;
    category: ServiceCategory;
    phone: string;
    registeredAt: bigint;
    location: string;
}
export interface UserProfile {
    name: string;
}
export enum ProviderStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ServiceCategory {
    plumber = "plumber",
    other = "other",
    hvac = "hvac",
    electrician = "electrician",
    nurse = "nurse",
    cleaner = "cleaner",
    painter = "painter",
    carpenter = "carpenter"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveProvider(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getApprovedProviders(): Promise<Array<ServiceProvider>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProvider(id: bigint): Promise<ServiceProvider | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listPendingProviders(): Promise<Array<ServiceProvider>>;
    registerProvider(name: string, email: string, phone: string, category: ServiceCategory, yearsExperience: bigint, location: string, availability: string, bio: string): Promise<bigint>;
    rejectProvider(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProviders(category: ServiceCategory | null, location: string | null): Promise<Array<ServiceProvider>>;
}
import type { ProviderStatus as _ProviderStatus, ServiceCategory as _ServiceCategory, ServiceProvider as _ServiceProvider, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveProvider(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveProvider(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getApprovedProviders(): Promise<Array<ServiceProvider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedProviders();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedProviders();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProvider(arg0: bigint): Promise<ServiceProvider | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvider(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvider(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listPendingProviders(): Promise<Array<ServiceProvider>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingProviders();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingProviders();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerProvider(arg0: string, arg1: string, arg2: string, arg3: ServiceCategory, arg4: bigint, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProvider(arg0, arg1, arg2, to_candid_ServiceCategory_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProvider(arg0, arg1, arg2, to_candid_ServiceCategory_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async rejectProvider(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectProvider(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchProviders(arg0: ServiceCategory | null, arg1: string | null): Promise<Array<ServiceProvider>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProviders(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProviders(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ProviderStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderStatus): ProviderStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceProvider_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceProvider): ServiceProvider {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceProvider]): ServiceProvider | null {
    return value.length === 0 ? null : from_candid_ServiceProvider_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    status: _ProviderStatus;
    yearsExperience: bigint;
    name: string;
    email: string;
    availability: string;
    category: _ServiceCategory;
    phone: string;
    registeredAt: bigint;
    location: string;
}): {
    id: bigint;
    bio: string;
    status: ProviderStatus;
    yearsExperience: bigint;
    name: string;
    email: string;
    availability: string;
    category: ServiceCategory;
    phone: string;
    registeredAt: bigint;
    location: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        status: from_candid_ProviderStatus_n6(_uploadFile, _downloadFile, value.status),
        yearsExperience: value.yearsExperience,
        name: value.name,
        email: value.email,
        availability: value.availability,
        category: from_candid_ServiceCategory_n8(_uploadFile, _downloadFile, value.category),
        phone: value.phone,
        registeredAt: value.registeredAt,
        location: value.location
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ProviderStatus {
    return "pending" in value ? ProviderStatus.pending : "approved" in value ? ProviderStatus.approved : "rejected" in value ? ProviderStatus.rejected : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    plumber: null;
} | {
    other: null;
} | {
    hvac: null;
} | {
    electrician: null;
} | {
    nurse: null;
} | {
    cleaner: null;
} | {
    painter: null;
} | {
    carpenter: null;
}): ServiceCategory {
    return "plumber" in value ? ServiceCategory.plumber : "other" in value ? ServiceCategory.other : "hvac" in value ? ServiceCategory.hvac : "electrician" in value ? ServiceCategory.electrician : "nurse" in value ? ServiceCategory.nurse : "cleaner" in value ? ServiceCategory.cleaner : "painter" in value ? ServiceCategory.painter : "carpenter" in value ? ServiceCategory.carpenter : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceProvider>): Array<ServiceProvider> {
    return value.map((x)=>from_candid_ServiceProvider_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory | null): [] | [_ServiceCategory] {
    return value === null ? candid_none() : candid_some(to_candid_ServiceCategory_n14(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    plumber: null;
} | {
    other: null;
} | {
    hvac: null;
} | {
    electrician: null;
} | {
    nurse: null;
} | {
    cleaner: null;
} | {
    painter: null;
} | {
    carpenter: null;
} {
    return value == ServiceCategory.plumber ? {
        plumber: null
    } : value == ServiceCategory.other ? {
        other: null
    } : value == ServiceCategory.hvac ? {
        hvac: null
    } : value == ServiceCategory.electrician ? {
        electrician: null
    } : value == ServiceCategory.nurse ? {
        nurse: null
    } : value == ServiceCategory.cleaner ? {
        cleaner: null
    } : value == ServiceCategory.painter ? {
        painter: null
    } : value == ServiceCategory.carpenter ? {
        carpenter: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
